# Generated by Django 4.0.4 on 2022-05-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Task Title', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('d_photo', models.ImageField(upload_to='designer/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(help_text='The price')),
                ('j_photo', models.ImageField(upload_to='jewelry/photos/')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='JewelryApp.designer')),
            ],
        ),
    ]
